onepiece.janus:
  # 接入渠道标识，请联系开放网关管理员分配
  channel: test
  # 签名类型，默认为“hmac_sha1”，请联系开放网关管理员分配
  sign-type: hmac_sha1
  # 签名密钥，请联系开放网关管理员分配
  sign-key: "0123456789"
  # （可选）验签密钥，用于验证网关返回报文的正确性，请联系开放网关管理员分配
  verify-key: "0123456789"